-- MySQL Script generated by MySQL Workbench
-- Tue Nov 15 13:47:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`central_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`central_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`central_type` (
  `id` INT NOT NULL COMMENT 'id typu centralki, dwa rodzaje:\n1. bramofon\n2. plot',
  `name` VARCHAR(45) NOT NULL COMMENT 'nazwa typu centralki',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`central`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`central` ;

CREATE TABLE IF NOT EXISTS `mydb`.`central` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT 'nazwa centrali (dla płotu maksymalnie 15 sztuk, dla bramofonu maksymalnie 2 sztuki modułów)',
  `central_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `central_type_id_idx` (`central_type_id` ASC) VISIBLE,
  CONSTRAINT `central_type_id`
    FOREIGN KEY (`central_type_id`)
    REFERENCES `mydb`.`central_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`message_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`message_type` (
  `id` INT NOT NULL COMMENT 'id typu komunikatu:\nkomunikat o wejściu na teren brelokiem RFID\n1. fotowoltaika\n2 - bezpieczeństwo, komunikat o wejściu na teren po rozpoznaniu twarzy\n3 - bezpieczeństwo, rozbrojenie alarmu\n4 - bezpieczeństwo, uzbrojenie alarmu\n5 - bezpieczeństwo, utrata energii - przejście na zasilanie bateryjne\n6 - bezpieczeństwo, uruchomienie urządzenia  \n7 - bezpieczeństwo, włamanie \n',
  `name` VARCHAR(100) NOT NULL COMMENT 'nazwa komunikatu',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`photovoltaics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`photovoltaics` ;

CREATE TABLE IF NOT EXISTS `mydb`.`photovoltaics` (
  `id` INT NOT NULL COMMENT 'Id komunikatu.',
  `central_id` INT NOT NULL COMMENT 'Id centralki.',
  `date` DATETIME NOT NULL COMMENT 'Data i czas wysłania komunikatu.',
  `power` DECIMAL(5,2) NOT NULL COMMENT 'moc [W]',
  `voltage` DECIMAL(5,2) NOT NULL COMMENT 'napięcie [V]',
  `amperage` DECIMAL(5,2) NULL COMMENT 'natężenie [A]',
  `message_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `central_id_idx` (`central_id` ASC) VISIBLE,
  INDEX `message_type_id_idx` (`message_type_id` ASC) VISIBLE,
  CONSTRAINT `central_id`
    FOREIGN KEY (`central_id`)
    REFERENCES `mydb`.`central` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `message_type_id`
    FOREIGN KEY (`message_type_id`)
    REFERENCES `mydb`.`message_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`module` ;

CREATE TABLE IF NOT EXISTS `mydb`.`module` (
  `id` INT NOT NULL COMMENT 'id modułu (dla płotu maksymalnie 15 sztuk, dla bramofonu maksymalnie 2 sztuki modułów w jednej centrali)',
  `name` VARCHAR(45) NOT NULL COMMENT 'nazwa modulu, moze sie zmieniac',
  `central_id` INT NOT NULL COMMENT 'id centrali',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `central_id_idx` (`central_id` ASC) VISIBLE,
  CONSTRAINT `central_id`
    FOREIGN KEY (`central_id`)
    REFERENCES `mydb`.`central` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`security`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`security` ;

CREATE TABLE IF NOT EXISTS `mydb`.`security` (
  `id` INT NOT NULL COMMENT 'id komunikatu',
  `central_id` INT NOT NULL COMMENT 'id centralki',
  `date` DATETIME NOT NULL COMMENT 'data wyslania komunikatu',
  `value` VARCHAR(45) NULL COMMENT 'wartosc komunikatu',
  `message_type_id` INT NOT NULL COMMENT 'id rodzaju komunikatu',
  PRIMARY KEY (`id`),
  INDEX `central_id_idx` (`central_id` ASC) VISIBLE,
  INDEX `message_type_id_idx` (`message_type_id` ASC) VISIBLE,
  CONSTRAINT `central_id`
    FOREIGN KEY (`central_id`)
    REFERENCES `mydb`.`central` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `message_type_id`
    FOREIGN KEY (`message_type_id`)
    REFERENCES `mydb`.`message_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`central_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`central_type` (`id`, `name`) VALUES (1, 'photovoltaics');
INSERT INTO `mydb`.`central_type` (`id`, `name`) VALUES (2, 'security');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`message_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`message_type` (`id`, `name`) VALUES (2, 'komunikat o wejściu na teren brelokiem RFID');
INSERT INTO `mydb`.`message_type` (`id`, `name`) VALUES (3, 'komunikat o wejściu na teren po rozpoznaniu twarzy');
INSERT INTO `mydb`.`message_type` (`id`, `name`) VALUES (4, 'rozbrojenie alarmu');
INSERT INTO `mydb`.`message_type` (`id`, `name`) VALUES (5, 'uzbrojenie alarmu');
INSERT INTO `mydb`.`message_type` (`id`, `name`) VALUES (6, 'utrata energii - przejście na zasilanie bateryjne');
INSERT INTO `mydb`.`message_type` (`id`, `name`) VALUES (7, 'uruchomienie urządzenia  ');
INSERT INTO `mydb`.`message_type` (`id`, `name`) VALUES (8, 'włamanie ');
INSERT INTO `mydb`.`message_type` (`id`, `name`) VALUES (1, 'photovoltaics');

COMMIT;

